# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jacky.Tu
description: '分享我在Web相關技術學習心得&生活札記' # write a nice description for your blog
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://tu-szu-chi.github.io' # the base hostname & protocol for your site http://www.example.com
google_analytics: 'UA-85774592-1'
facebook_username: 'zuchi.tu'

# Build settings
markdown: kramdown

permalink: pretty

gems: [jekyll-paginate]

paginate: 3
